service: serverless-to-do-list

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET

plugins:
  - serverless-mocha-plugin
